### PR TITLE
Leverage dsbulk string codecs to convert from strings to Java types (and back again)

### LINKED ISSUE #484: Parsing vector data from JSON fails for "floats" with too many digits (aka doubles)
When ingesting `VECTOR<FLOAT,n>` data from a JSON, dsbulk (v 1.11) fails for "floats" which are represented with too many digits. They end up being double, which seems to cause unrecoverable problems then.

### Notes:

1. JSON produced by dsbulk itself are OK, i.e. their floats are floats proper (low number of digits).
2. But, with folks coming to load datasets generated elsewhere (viz Python, which lacks a clear float/double distinction) this limitation might get in the way.

### Minimal reproducible case

```
create table mini_table (id text primary key, embedding vector<float, 2>);
```

```
java -jar dsbulk-1.11.0.jar load -k $KEYSPACE -t mini_table -u "token" -p $TOKEN -b $BUNDLEZIP --dsbulk.connector.json.mode SINGLE_DOCUMENT --connector.json.url GOOD_OR_BAD.json -c json
```

```
$> cat good.json 
[
 {
  "id": "my_row",
  "embedding": [
   6.64632,
   4.49715
  ]
 }
]

$> cat bad.json 
[
 {
  "id": "my_row",
  "embedding": [
   6.646329843,
   4.4971533213
  ]
 }
]
```

### PR DESCRIPTION
**Pull request by absurdfarce**
dsbulk codecs for Strings enforce additional constraints on their input values (like overflow checks for numerical values) that we want to be able to leverage when dealing with vectors.  This change accomplishes that by implementing a variant of the CQLVector.from() logic directly within the codec infrastructure of dsbulk.

The JSON vector codec was already using dsbulk JSON codecs so that path appears to be fine.

Also added some test cases to demonstrate the expected behaviour.

### CODE REVIEW

File: codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java [hunk 1]
```diff
@@ -17,18 +17,42 @@
...
+
+    // Logic below adapted from VectorCodec.parse() and CqlVector.from() but here we use the dsbulk
+    // codecs for the subtype in order to enforce any additional behaviours
+    //
+    // Logically this probably makes more sense anyway.  It's the responsibilty of dsbulk to define
+    // what sorts of formats it wants to support for vectors.  It can certainly re-use a
+    // representation
+    // known to work with vectors but it certainly isn't obligated to do so.
+    if (s == null || s.isEmpty() || s.equalsIgnoreCase("NULL")) return null;
+    ArrayList<SubtypeT> vals =
```
Comment (adutra) [inline codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java]: This doesn't look 100% right to me.

If you are going down the path of having a subcodec – which I think is the right thing to do btw – then I would suggest to go even further: here, you are using a string codec to parse N elements of the vector. Because of that, you need to handle the collection manually, by stripping the first and last character of the input, which are assumed to be the collection delimiters.

But instead, I think you should use a _collection codec_ that would parse the _entire_ collection for you. That collection codec would in turn use another inner codec to parse the elements.

Comment (absurdfarce) [reply codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java]: If I understand correctly you're thinking of something more like this then?

```java
public class StringToVectorCodec<SubtypeT extends Number>
    extends StringToCollectionCodec<SubtypeT, CqlVector<SubtypeT>> {
...
}
```

If so then we have an issue with the underlying Java type: CqlVector [implements Iterable but doesn't implement Collection](https://github.com/apache/cassandra-java-driver/blob/4.18.1/core/src/main/java/com/datastax/oss/driver/api/core/data/CqlVector.java#L50-L55), so it can't satisfy the type bounds in question.  The rationale here was that CqlVector is closer to an array than a Collection type so implementing Collection would be somewhat confusing.  I readily agree there's room for debate here but it is the state of the world as of 4.18.1.

Does that fact change your analysis?  It seems like there are at least three paths forward here:

1. Make CqlVector implement Collection.  Would require a new Java driver release + a dsbulk update to use the new version.
2. Adapt the JSON parsing logic in StringToCollectionCodec to be used here instead of the manual process.  Provides similar parsing behaviour to what dsbulk currently exhibits for collections without the need for a driver upgrade at the cost of some code duplication.
3. Leave it as-is, possibly with a ticket for future work

I'm not opposed to any of these options, although (1) will certainly take more time than the other two.

Thoughts?

Comment (adutra) [reply codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java]: @absurdfarce here is what I had in mind:

https://github.com/datastax/dsbulk/compare/issue484...adutra:dsbulk:issue484

It's loosely inspired by how `StringToMapCodec` is designed.

Also, it adheres to the general principle in dsbulk that mandates that all complex codecs rely in a standard _json_ representation of the data, and not their CQL representation. So here `StringToVectorCodec` relies on a json codec that outputs a json array of the vector dimensions.

Let me know if that looks better.

Comment (absurdfarce) [reply codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java]: **Ohhhhh**, I see what you mean now.  Yeah, this makes _a ton_ more sense than my original suggestion!  I'm gonna make a PR out of that diff and merge it in here; there are several improvements in there I'd like to get into this work.

Many thanks, my friend; that diff absolutely crystalized exactly what you were talking about!

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java [hunk 2]
```diff
@@ -22,26 +22,45 @@
...
+
+  @BeforeEach
+  void setUp() {
+    ConversionContext context = new TextConversionContext().setNullStrings("NULL");
+    ConvertingCodecFactory codecFactory = new ConvertingCodecFactory(context);
+    codec =
+        (StringToVectorCodec<Float>)
+            codecFactory.<String, CqlVector<Float>>createConvertingCodec(
+                DataTypes.vectorOf(DataTypes.FLOAT, 5), GenericType.STRING, true);
+  }
```
Comment (absurdfarce) [inline codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java:53]: This is a _much_ cleaner way to get to a workable ConversionContext! :+1:

File: codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java [hunk 3]
```diff
@@ -17,22 +17,57 @@
...
   @Override
   public CqlVector<SubtypeT> externalToInternal(String s) {
-    return this.internalCodec.parse(s);
+    if (isNullOrEmpty(s)) {
+      return null;
+    }
+    try {
+      JsonNode node = objectMapper.readTree(StringUtils.ensureBrackets(s));
+      List<SubtypeT> vals = jsonCodec.externalToInternal(node);
+      return CqlVector.newInstance(vals);
```
Comment (absurdfarce) [inline codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodec.java:53]: Use JSON codecs to eval input strings as JSON, build a list from that and then build a CqlVector from that list.  This makes behaviour of the vector codec consistent with codecs for the collection types by enforcing a common policy around string representations of these types (i.e. they have to be JSON-friendly).

Idea (and implementation) provided by @adutra

File: codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringConvertingCodecProvider.java [hunk 4]
```diff
@@ -335,11 +335,15 @@ public class StringConvertingCodecProvider implements ConvertingCodecProvider {
...
+                  new VectorCodec<>(
                       vectorType,
-                      codecFactory.getCodecRegistry().codecFor(vectorType.getElementType())),
-                  nullStrings);
+                      codecFactory.getCodecRegistry().codecFor(vectorType.getElementType()));
+              ConvertingCodec<JsonNode, List<Number>> jsonCodec =
+                  codecFactory.createConvertingCodec(
+                      DataTypes.listOf(vectorType.getElementType()), JSON_NODE_TYPE, false);
+              return new StringToVectorCodec<>(
+                  vectorCodec, jsonCodec, context.getAttribute(OBJECT_MAPPER), nullStrings);
```
Comment (absurdfarce) [inline codecs/text/src/main/java/com/datastax/oss/dsbulk/codecs/text/string/StringConvertingCodecProvider.java:346]: See StringToVectorCodec changes below.  jsonCodec is here to convert raw string values into Lists; StringToVectorCodec builds CqlVectors out of them.

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java [hunk 5]
```diff
@@ -53,39 +72,46 @@ void should_convert_from_valid_external() {
...
+    assertThatThrownBy(() -> codec.encode(tooFewString, ProtocolVersion.DEFAULT))
         .isInstanceOf(IllegalArgumentException.class);
   }
+
+  // Issue 484: now that we're using the dsbulk string-to-subtype converters we should get
+  // enforcement of existing dsbulk policies.  For our purposes that means the failure on
+  // arithmetic overflow.
+  @Test
+  void should_not_convert_too_much_precision() {
+    assertThatThrownBy(() -> codec.encode("6.646329843", ProtocolVersion.DEFAULT))
```
Comment (absurdfarce) [inline codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java]: I'd argue this is incorrect.  This test is intended to mirror the equivalent test in JsonNodeToVectorCodecTest.  In that case we're trying to confirm that the JSON representation for an otherwise valid vector (really just a JSON array in that case) fails to convert because precision policies in the dsbulk codecs are being enforced.  If we want to model the same thing here this should be the string representation for an otherwise valid vector... which means it should be something like:

```java
  // Issue 484: now that we're using the dsbulk string-to-subtype converters we should get
  // enforcement of existing dsbulk policies.  For our purposes that means the failure on
  // arithmetic overflow.
  @Test
  void should_not_convert_too_much_precision() {
    assertThatThrownBy(() -> codec.encode("[1.1, 2.2, 3.3, 6.646329843]", ProtocolVersion.DEFAULT))
        .isInstanceOf(ArithmeticException.class);
  }
```

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java [hunk 6]
```diff
@@ -53,39 +72,46 @@ void should_convert_from_valid_external() {
...
         .toExternal("NULL");
-
-    // We should encode
   }
 
   @Test
-  void should_not_convert_from_invalid_internal() {
-    assertThat(dsbulkCodec).cannotConvertFromInternal("not a valid vector");
+  void should_not_convert_from_invalid_external() {
+    assertThat(codec).cannotConvertFromExternal("[6.646329843]");
```
Comment (absurdfarce) [inline codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java:92]: This effectively winds up duplicating should_not_convert_too_much_precision() in a way that isn't very clear.  The original intent of this method was to perform something similar to JsonNodeToVectorCodecTest.should_not_convert_from_invalid_internal(), specifically given something that isn't a CqlVector this method fails completely.  We could certainly add a few more cases but I'd argue it's worthwhile to preserve the symmetry.

**Comment by absurdfarce** [comment]
Pulled in changes from @adutra 's branch; this makes the usage of codecs in vector parsing much more consistent with existing dsbulk code.  I have a few nits about tests that I'd like to hash out with @adutra but that's all that's left.

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/json/JsonNodeToVectorCodecTest.java [hunk 7]
```diff
@@ -104,4 +104,16 @@ void should_encode_too_many_but_not_too_few() {
...
   }
+
+  /* Issue 484: now that we're using the dsbulk string-to-subtype converters we should get
+   * enforcement of existing dsbulk policies.  For our purposes that means the failure on
+   * arithmetic overflow */
+  @Test
+  void should_not_convert_too_much_precision() {
+    ArrayNode tooPreciseNode = JSON_NODE_FACTORY.arrayNode();
+    tooPreciseNode.add(JSON_NODE_FACTORY.numberNode(6.646329843));
+    assertThat(dsbulkCodec).cannotConvertFromInternal(tooPreciseNode);
```
Comment (adutra) [inline codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/json/JsonNodeToVectorCodecTest.java]: Hmm I don't get why you are trying to use `dsbulkCodec` to convert from an _internal_ type that would be... `JsonNode`? 

The internal type of this codec is `CqlVector`, so calling `cannotConvertFromInternal` would make sense only
if you had some instance of `CqlVector` that is somehow "invalid" – maybe a `CqlVector` with the wrong number of dimensions, or something like that.

But calling `cannotConvertFromInternal(tooPreciseNode)` does not make sense to me. It's only possible, btw, because `dsbulkCodec` is of the raw type `JsonNodeToVectorCodec`. It should be `JsonNodeToVectorCodec<Float>` – but in that case, I bet this statement wouldn't compile anymore.

If you are trying to check whether the _external_ type `tooPreciseNode` causes a runtime error, then call `cannotConvertFromExternal(tooPreciseNode)` – I fixed something similar for `StringToVectorCodecTest`, see test `should_not_convert_from_invalid_external`.

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java (hunk 5 above)
Comment (adutra) [reply codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java]: Your example if fine, but the current one is too. In DSBulk, enclosing brackets and braces are generally optional. So `codec.encode("6.646329843", ProtocolVersion.DEFAULT))` should behave like `codec.encode("[6.646329843]", ProtocolVersion.DEFAULT))`. You can add both tests btw.

But note that this test is almost identical to `should_not_convert_from_invalid_external`. Maybe merge both into one single test?

Comment (absurdfarce) [reply codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java]: Agreed, I think that makes a lot more sense @adutra

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/json/JsonNodeToVectorCodecTest.java (hunk 7 above)
Comment (absurdfarce) [reply codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/json/JsonNodeToVectorCodecTest.java]: Fair points all.  I'll fix these in another commit later on tonight.

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java (hunk 6 above)
Comment (absurdfarce) [reply codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/string/StringToVectorCodecTest.java:92]: This has now been resolved by more recent changes

File: codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/json/JsonNodeToVectorCodecTest.java (hunk 7 above)
Comment (absurdfarce) [reply codecs/text/src/test/java/com/datastax/oss/dsbulk/codecs/text/json/JsonNodeToVectorCodecTest.java]: Fixed in most recent push.

**Comment by absurdfarce** [comment]
Okay @adutra, I believe all outstanding issues have now been addressed.  Please take another pass at this when you have time and let me know if you agree or if you think there's still fixes to be made here.

**Review by adutra — APPROVED** [review]

**Comment by adutra** [comment]
LGTM @absurdfarce !

**Comment by absurdfarce** [comment]
Re-ran Jenkins run after most recent changes just to make sure everything is green.  With a 👍 from @adutra plus the green test run I'm calling this good.
