### PR TITLE
Increment records/failed counter for failed writes

### LINKED ISSUE #444: Display bug in console metrics reporter for the number of failed operations
After finishing a long-running (16 hours+) job, we got the following output:

```$ java -jar ~/dsbulk-1.10.0-SNAPSHOT.jar load --dsbulk.executor.maxPerSecond=10000 -url file:///mnt/data/toload -k testks -t dsbulk_test -b ~/secureBundle_prod.zip -u xxx -p xxx
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
Operation directory: /mnt/data/logs/LOAD_20220808-171139-742199
      total | failed | rows/s | p50ms | p99ms | p999ms | batches
600,000,000 |      0 | 10,005 |  2.11 | 10.81 |  20.32 |    1.00
Operation LOAD_20220808-171139-742199 completed with 76 errors in 16 hours, 39 minutes and 29 seconds.
Rejected records can be found in the following file(s): load.bad
Errors are detailed in the following file(s): load-errors.log
A summary of the operation in CSV format can be found in summary.csv.
```

There is a discrepancy between the reported number of failed records in the table (0) and the 76 errors in the final summary.

From the following `operations.log` you can see the discrepancy as well.

```ubuntu@ip-172-31-94-145:/mnt/data/logs/LOAD_20220808-171139-742199$ cat operation.log
2022-08-08 17:11:39 INFO  Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
2022-08-08 17:11:39 INFO  A cloud secure connect bundle was provided: ignoring all explicit contact points.
2022-08-08 17:11:39 INFO  A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
2022-08-08 17:11:39 INFO  Operation directory: /mnt/data/logs/LOAD_20220808-171139-742199
2022-08-09 09:51:11 WARN  Operation LOAD_20220808-171139-742199 completed with 76 errors in 16 hours, 39 minutes and 29 seconds.
2022-08-09 09:51:11 INFO  Records: total: 600,000,000, successful: 600,000,000, failed: 0
2022-08-09 09:51:11 INFO  Batches: total: 600,000,000, size: 1.00 mean, 1 min, 1 max
2022-08-09 09:51:11 INFO  Memory usage: used: 3,424 MB, free: 1,469 MB, allocated: 4,894 MB, available: 7,828 MB, total gc count: 23,256, total gc time: 379,839 ms
2022-08-09 09:51:11 INFO  Writes: total: 600,000,000, successful: 599,999,924, failed: 76, in-flight: 0
2022-08-09 09:51:11 INFO  Throughput: 10,005 writes/second
2022-08-09 09:51:11 INFO  Latencies: mean 2.11, 75p 2.29, 99p 10.81, 999p 20.32 milliseconds
2022-08-09 09:51:13 INFO  Final stats:
2022-08-09 09:51:13 INFO  Records: total: 600,000,000, successful: 600,000,000, failed: 0
2022-08-09 09:51:13 INFO  Batches: total: 600,000,000, size: 1.00 mean, 1 min, 1 max
2022-08-09 09:51:13 INFO  Memory usage: used: 3,430 MB, free: 1,463 MB, allocated: 4,894 MB, available: 7,828 MB, total gc count: 23,256, total gc time: 379,839 ms
2022-08-09 09:51:13 INFO  Writes: total: 600,000,000, successful: 599,999,924, failed: 76, in-flight: 0
2022-08-09 09:51:13 INFO  Throughput: 10,005 writes/second
2022-08-09 09:51:13 INFO  Latencies: mean 2.11, 75p 2.29, 99p 10.81, 999p 20.32 milliseconds
2022-08-09 09:51:13 INFO  Rejected records can be found in the following file(s): load.bad
2022-08-09 09:51:13 INFO  Errors are detailed in the following file(s): load-errors.log
2022-08-09 09:51:13 INFO  A summary of the operation in CSV format can be found in summary.csv.
```

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-47) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by adutra**
Fixes #444.

### CODE REVIEW

File: workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/metrics/MetricsManager.java [hunk 1]
```diff
@@ -457,13 +459,31 @@ public <T> Function<Flux<T>, Flux<T>> newTotalItemsMonitor() {
     return upstream -> upstream.doOnNext(item -> totalItems.inc());
   }
 
-  public <T> Function<Flux<T>, Flux<T>> newFailedItemsMonitor() {
+  public Function<Flux<Record>, Flux<Record>> newFailedRecordsMonitor() {
```
Comment (adutra) [inline workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/metrics/MetricsManager.java:474]: This change wasn't strictly required but I thought it would make things clear to distinguish the generic "failed items monitor" into 3 monitors: failed records, unmappable statements, and failed read/write results.

File: workflow/load/src/main/java/com/datastax/oss/dsbulk/workflow/load/LoadWorkflow.java [hunk 2]
```diff
@@ -234,6 +237,7 @@ public boolean execute() {
     statements
         .transform(this::executeStatements)
         .transform(queryWarningsHandler)
+        .transform(failedWritesMonitor)
```
Comment (adutra) [inline workflow/load/src/main/java/com/datastax/oss/dsbulk/workflow/load/LoadWorkflow.java:239]: This was the root cause of the bug: the monitor that increments the `records/failed` metric wasn't being invoked here, and so failed writes weren't being accounted for.

File: runner/src/it/java/com/datastax/oss/dsbulk/runner/simulacron/CSVEndToEndSimulacronIT.java [hunk 3]
```diff
@@ -733,7 +738,7 @@ public Publisher<Publisher<Record>> read(
     assertStatus(status, STATUS_COMPLETED_WITH_ERRORS);
     assertThat(logs.getAllMessagesAsString())
         .contains("completed with 11000 errors")
-        .contains("Records: total: 100,000, successful: 90,000, failed: 10,000")
+        .contains("Records: total: 100,000, successful: 89,000, failed: 11,000")
```
Comment (adutra) [inline runner/src/it/java/com/datastax/oss/dsbulk/runner/simulacron/CSVEndToEndSimulacronIT.java:741]: This bug report unveiled a flaw in this existing assertion.

File: workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/metrics/MetricsManager.java (hunk 1 above)
Comment (weideng1) [reply workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/metrics/MetricsManager.java:474]: Given this change, does it make sense to add a paragraph of comment to explain what these three types of "failed items" are?

**Comment by weideng1** [comment]
I've now tested the new binary built from this branch, and can see console reporter correctly showing the number of failed operations. LGTM

**Review by weideng1 — APPROVED** [review]
