### PR TITLE
Ability to resume a failed operation using checkpoint files

### LINKED ISSUE #431: Ability to resume a failed operation
This has been asked a few times:

* #395
* #396
* [DAT-324](https://datastax.jira.com/browse/DAT-324)

This is finally going to be possible for all workloads thanks to the work under review for #429 (see #430).

With the new summary.csv file being produced for all operations, we now must add a new option to resume a failed operation by parsing that file and and only re-attempting the resources that weren't read or written entirely.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-40) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by adutra**
Fixes #431.

### CODE REVIEW

File: workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/log/LogManager.java [hunk 1]
```diff
@@ -241,9 +252,12 @@ public void reportAvailableFiles() throws IOException {
...
     }
-    if (!resources.isEmpty()) {
-      writeSummaryFile();
-      LOGGER.info("A summary of the operation in CSV format can be found in {}.", SUMMARY_CSV);
+    if (checkpointEnabled) {
+      CheckpointManager manager = mergeCheckpointManagers();
+      if (!manager.isEmpty()) {
+        writeCheckpointFile(manager);
+        LOGGER.info("Checkpoints for the current operation were written to {}.", CHECKPOINT_CSV);
+      }
```
Comment (weideng1) [inline workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/log/LogManager.java:263]: Does it make sense to add another line in the log with something like the following, so that the user won't have to look up in the manual on how to leverage this checkpoint file?

`LOGGER.info("To resume the current operation, add the following command line flag --dsbulk.log.checkpoint.file={} .", CHECKPOINT_CSV);`

Comment (adutra) [reply workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/log/LogManager.java:263]: Yes, good idea. I also think we should skip this message completely if the operation completed successfully, wdyt? It doesn't make any sense to resume a completed operation.

Comment (weideng1) [reply workflow/commons/src/main/java/com/datastax/oss/dsbulk/workflow/commons/log/LogManager.java:263]: Agreed. If the job didn't get interrupted, it will be confusing to see this message.

**Review by weideng1 — APPROVED** [review]
I've tested the new resume feature with a failed job and I was able to get it to pick up where it left off. LGTM
